version: '3'

services:
  redis:
    image: redis
    ports:
      - '6378:6379'
  postgres:
    image: postgres
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: sonarium
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: sonarium-backend
